groups:
  - name: nginx-alerts
    rules:
      - alert: NginxDown
        expr: probe_success == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "NGINX is down"
          description: "Nginx is not responding for 15s"
